# Generated by Django 4.0.4 on 2022-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(default='', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('latestTweetId', models.CharField(default='', max_length=50)),
                ('wikiTimestamp', models.BigIntegerField(default=0)),
                ('showTweetCount', models.BooleanField(default=True)),
                ('isListMode', models.BooleanField(default=False)),
                ('twitterId', models.CharField(default='Twitter', max_length=50)),
                ('feedTitle', models.CharField(default='Tweets', max_length=50)),
                ('lastUpdate', models.BigIntegerField(default=0)),
            ],
        ),
    ]
