# Generated by Django 4.0.4 on 2022-05-08 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='widgetMembers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Twitter', max_length=50), default=[], size=None),
        ),
    ]
