# Generated by Django 4.0.4 on 2022-05-08 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_subreddit_widgetmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='widgetMembers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Twitter', max_length=50), default=list, size=None),
        ),
    ]
