# Generated by Django 4.0.4 on 2022-05-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_subreddit_widgetmembersprofileurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddit',
            old_name='widgetMembersProfileUrls',
            new_name='widgetProfileUrls',
        ),
    ]
