# Generated by Django 4.0.4 on 2022-05-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_rename_widgetmembersprofileurls_subreddit_widgetprofileurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='widgetProfileImageData',
            field=models.JSONField(default=list),
        ),
    ]
