# Generated by Django 4.0.4 on 2022-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_subreddit_nextupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='nextImageUploadTimestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
