# Generated by Django 4.0.4 on 2022-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_subreddit_nextimageuploadtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='bugFixImageUpload',
            field=models.BooleanField(default=False),
        ),
    ]
