# Generated by Django 4.0.4 on 2022-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_subreddit_bugfiximageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='showReplies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='showReweets',
            field=models.BooleanField(default=True),
        ),
    ]
